### ISSUE TITLE
Suggestion for documentation approvements

### ISSUE THREAD

**Issue by mitomm** [furzeface/gulp-cache-bust#15]
So, now that I got this thing working, I really like. 

However, I lost a tremendous amount of time figuring out why the path couldn't be resolve. I was almost giving up on this library, before I decided to check the source code in more detail.

Seems like you can just pass a basePath as an option that fixes all my issues.

Unfortunately it is nowhere mentioned in the docs.

I guess this might be quite helpful for future users to add it to the official documentation.

**Comment by davinkevin** [comment]
I am totally agree with you because I have seen the same error in my env...

PR are welcomed and I will try to work on this, this week end.

**Comment by ilmartyrk** [comment]
This missing `basePath` property was the main reason for it breaking in the cachebust 2.0.1. That's because in the previous version the hash was created from the filename so if you made any changes to the files this hash would never be renewed. In the new version hash is created from the file content and `basePath` prop. is used to define parent files location. Thumbs up for adding this to docs.
